def month_map():
    import calendar
    return dict(enumerate(calendar.month_abbr))


def day_map():
    import calendar
    return dict(enumerate(calendar.day_name))


def make_map():
    return {
        1: "American Motors",
        2: "Jeep/Kaiser-Jeep/Willys Jeep",
        3: "AM General",
        6: "Chrysler",
        7: "Dodge",
        8: "Imperial",
        9: "Plymouth",
        10: "Eagle",
        12: "Ford",
        13: "Lincoln",
        14: "Mercury",
        18: "Buick/Opel",
        19: "Cadillac",
        20: "Chevrolet",
        21: "Oldsmobile",
        22: "Pontiac",
        23: "GMC",
        24: "Saturn",
        25: "Grumman",
        26: "Coda (Since 2013)",
        29: "Other Domestic, includes(Tesla)",
        30: "Volkswagen",
        31: "Alfa Romeo",
        32: "Audi",
        33: "Austin/Austin Healey",
        34: "BMW",
        35: "Datsun/Nissan",
        36: "Fiat",
        37: "Honda",
        38: "Isuzu",
        39: "Jaguar",
        40: "Lancia",
        41: "Mazda",
        42: "Mercedes-Benz",
        43: "MG",
        44: "Peugeot",
        45: "Porsche",
        46: "Renault",
        47: "Saab",
        48: "Subaru",
        49: "Toyota",
        50: "Triumph",
        51: "Volvo",
        52: "Mitsubishi",
        53: "Suzuki",
        54: "Acura",
        55: "Hyundai",
        56: "Merkur",
        57: "Yugo",
        58: "Infiniti",
        59: "Lexus",
        60: "Daihatsu",
        61: "Sterling",
        62: "Land Rover",
        63: "Kia",
        64: "Daewoo",
        65: "Smart (Since 2010)",
        66: "Mahindra (2011-2013)",
        67: "Scion (Since 2012)",
        69: "Other Imports",
        70: "BSA",
        71: "Ducati",
        72: "Harley-Davidson",
        73: "Kawasaki",
        74: "Moto Guzzi",
        75: "Norton",
        76: "Yamaha",
        77: "Victory",
        78: "Other Make Moped (Since 2010)",
        79: "Other Make Motored Cycle (Since 2010)",
        80: "Brockway",
        81: "Diamond Reo/Reo",
        82: "Freightliner",
        83: "FWD",
        84: "International Harvester/Navistar",
        85: "Kenworth",
        86: "Mack",
        87: "Peterbilt",
        88: "Iveco/Magirus",
        89: "White/Autocar, White/GMC",
        90: "Bluebird",
        91: "Eagle Coach",
        92: "Gillig",
        93: "MCI",
        94: "Thomas Built",
        97: "Not Reported (Since 2010)",
        98: "Other Make",
        99: "unknown"
    }


def route_map():
    return {
        1: "Interstate",
        2: "U.S.Highway",
        3: "State Highway",
        4: "County Road",
        5: "Local Street – Township",
        6: "Local Street – Municipality",
        7: "Local Street – Frontage",
        8: "Other",
        9: "Unknown",
    }


def rur_urb_map():
    return {
        1: "Rural",
        2: "Urban",
        6: "Trafficway Not in State Inventory",
        8: "Not Reported",
        9: "Unknown",
    }

def state_map():
    return{
        1: "Alabama",
        31: "Nebraska",
        2: "Alaska",
        32: "Nevada",
        4: "Arizona",
        33: "New Hampshire",
        5: "Arkansas",
        34: "New Jersey",
        6: "California",
        35: "New Mexico",
        8: "Colorado",
        36: "New York",
        9: "Connecticut",
        37: "North Carolina",
        10: "Delaware",
        38: "North Dakota",
        11: "District of Columbia",
        39: "Ohio",
        12: "Florida",
        40: "Oklahoma",
        13: "Georgia",
        41: "Oregon",
        15: "Hawaii",
        42: "Pennsylvania",
        16: "Idaho",
        43: "Puerto Rico",
        17: "Illinois",
        44: "Rhode Island",
        18: "Indiana",
        45: "South Carolina",
        19: "Iowa",
        46: "South Dakota",
        20: "Kansas",
        47: "Tennessee",
        21: "Kentucky",
        48: "Texas",
        22: "Louisiana",
        49: "Utah",
        23: "Maine",
        50: "Vermont",
        24: "Maryland",
        52: "Virgin Islands(since 2004)",
        25: "Massachusetts",
        51: "Virginia",
        26: "Michigan",
        53: "Washington",
        27: "Minnesota",
        54: "West Virginia",
        28: "Mississippi",
        55: "Wisconsin",
        29: "Missouri",
        56: "Wyoming",
        30: "Montana",
    }

